version: "3.3"

services:
  app:
    container_name: nodemysql
    image: nodemysql:12.0
    ports:
      - 3000:3000
    depends_on:
      - mysql_server
  mysql_server:
    container_name: mysqldb2
    image: mysql
    environment: 
      - MYSQL_ROOT_PASSWORD=root